change cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -11,20 +11,26 @@ jobs:
     steps:
       - name: Checkout Source
         uses: actions/checkout@v4
-      - name: Login to docker hub
-        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
+        
+      - name: Login to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+        
       - name: Build Docker Image
-        run: docker build -t integrationninjas/nodejs-app  .
-      - name: Publish Image to docker hub
+        run: docker build -t integrationninjas/nodejs-app:latest .
+        
+      - name: Publish Image to Docker Hub
         run: docker push integrationninjas/nodejs-app:latest 
- 
+
   deploy:
     needs: build
     runs-on: self-hosted 
     steps:
-      - name: Pull image from docker hub
+      - name: Pull Image from Docker Hub
         run: docker pull integrationninjas/nodejs-app:latest 
-      - name: Delete old container
-        run: docker rm -f nodejs-app-container  
+        
+      - name: Delete Old Container
+        run: docker rm -f nodejs-app-container || true  # Added || true to avoid failure if the container doesn't exist
+        
       - name: Run Docker Container
-        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' integrationninjas/nodejs-app
+        run: |
+          docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' integrationninjas/nodejs-app:latest
